app = "tensil-ai"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  NODE_ENV = "production"
  DB_HOST = "localhost"
  DB_PORT = "5432"
  DB_USER = "postgres"
  DB_PASSWORD = "postgres"
  DB_DATABASE = "app"
  APP_KEY = "OAShAapMVjwcKjjgAP6CFxy5lKGc_Lg_"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"

[[mounts]]
  source = "postgres_data"
  destination = "/var/lib/postgresql/data"
