# fly.toml app configuration file generated for tensil-ai on 2025-06-07T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tensil-ai'
primary_region = 'dfw'

[build]

[env]
  NODE_ENV = 'production'
  NEXT_TELEMETRY_DISABLED = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/public'
