app = 'tensil-ai'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = 'production'
  MONGODB_URI = 'mongodb://localhost:27017/tensil-ai'
